# For full config options, check the docs:
#    docs.serverless.com

service: why82-calc

plugins:
  - python-deps
  - serverless-plugin-write-env-vars

custom:
  writeEnvVars:
    BUCKET_NAME: ${self:service}-${opt:stage, self:provider.stage}
    CURRENT_SEASON: 2016

provider:
  name: aws
  runtime: python2.7
  region: us-west-2
  timeout: 30
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        Fn::Join:
          - ''
          - - "arn:aws:s3:::"
            - Ref: DataBucket
            - '/*'

package:
  exclude:
    - tests
    - out
    - .idea
    - .vagrant
    - why82.tar.gz
    - invoke.yaml
    - README.md
    - LICENSE
    - deps_package.sh
    - deps_pull.sh
    - deps_setup.sh
    - Vagrantfile
    - .DS_Store
    - node_modules
    - package.json
    - .coverage
    - why82.lambda.iml
    - __pycache__
    - python-deps

functions:
  tiers:
    handler: calc_tiers.lambda_handler
  schedule:
    handler: calc_schedule.lambda_handler

resources:
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${opt:stage, self:provider.stage}
        CorsConfiguration:
          CorsRules:
            - MaxAge: 3600
              AllowedOrigins:
                - http://*.why82.com
              AllowedMethods:
                - GET
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:*
              Function:
                'Fn::GetAtt':
                  - ScheduleLambdaFunction
                  - Arn
              Filter:
                S3Key:
                  Rules:
                    - Name: suffix
                      Value: '-tiers.json'
    ScheduleLambdaPermissionS3:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          'Fn::GetAtt':
            - ScheduleLambdaFunction
            - Arn
        Action: lambda:InvokeFunction
        Principal: s3.amazonaws.com
    TiersLambdaPermissionS3:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          'Fn::GetAtt':
            - TiersLambdaFunction
            - Arn
        Action: lambda:InvokeFunction
        Principal: s3.amazonaws.com

  Outputs:
     DataBucket:
       Description: 'The bucket where stats will be stored'
       Value:
         Ref: DataBucket
